/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego-CT
 */
public class ExPT5 extends javax.swing.JFrame {

    /**
     * Creates new form ExPT5
     */
    public ExPT5() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private Set<String> convertirTextoAConjunto(String texto) {
    Set<String> conjunto = new HashSet<>();
    if (texto != null && !texto.trim().isEmpty()) {
        String[] elementos = texto.split(",");
        for (String elem : elementos) {
            conjunto.add(elem.trim());
        }
    }
    return conjunto;
}

// Convierte Set<String> a String bonito
private String conjuntoAString(Set<String> conjunto) {
    if (conjunto.isEmpty()) return "{ }";
    return conjunto.toString();
}

// Operaciones
private Set<String> calcularUnion(Set<String> L1, Set<String> L2) {
    Set<String> res = new HashSet<>(L1);
    res.addAll(L2);
    return res;
}

private Set<String> calcularInterseccion(Set<String> L1, Set<String> L2) {
    Set<String> res = new HashSet<>(L1);
    res.retainAll(L2);
    return res;
}

private Set<String> calcularDiferencia(Set<String> L1, Set<String> L2) {
    Set<String> res = new HashSet<>(L1);
    res.removeAll(L2);
    return res;
}

private Set<String> calcularConcatenacion(Set<String> L1, Set<String> L2) {
    Set<String> res = new HashSet<>();
    for (String s1 : L1) {
        for (String s2 : L2) {
            res.add(s1 + s2);
        }
    }
    return res;
}

private Set<String> calcularPotencia(Set<String> L, int n) {
    if (n == 0) return new HashSet<>(Collections.singleton("ε"));
    Set<String> resultado = new HashSet<>(L);
    for (int i = 1; i < n; i++) {
        Set<String> temp = new HashSet<>();
        for (String s1 : resultado) {
            for (String s2 : L) {
                temp.add(s1 + s2);
            }
        }
        resultado = temp;
    }
    return resultado;
}

private Set<String> calcularInverso(Set<String> L) {
    Set<String> res = new HashSet<>();
    for (String s : L) {
        res.add(new StringBuilder(s).reverse().toString());
    }
    return res;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLenguaje1 = new javax.swing.JTextField();
        txtLenguaje2 = new javax.swing.JTextField();
        txtPotencia = new javax.swing.JTextField();
        btnUnion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        BtnInterseccion = new javax.swing.JButton();
        btndiferencia = new javax.swing.JButton();
        btnConcatenacion = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnInverso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtLenguaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLenguaje2ActionPerformed(evt);
            }
        });

        btnUnion.setText("Union");
        btnUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnionActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        BtnInterseccion.setText("Interseccion");
        BtnInterseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInterseccionActionPerformed(evt);
            }
        });

        btndiferencia.setText("Diferencia");
        btndiferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiferenciaActionPerformed(evt);
            }
        });

        btnConcatenacion.setText("Concatenacion");
        btnConcatenacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcatenacionActionPerformed(evt);
            }
        });

        btnPotencia.setText("Potencia");
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });

        btnInverso.setText("Inverso");
        btnInverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese su lenguaje 1:");

        jLabel2.setText("Ingrese su lenguaje 2:");

        jLabel3.setText("Ingrese una potencia:");

        jButton1.setText("Volver al menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(619, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLenguaje1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLenguaje2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPotencia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUnion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnInterseccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btndiferencia)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConcatenacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPotencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInverso)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLenguaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLenguaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUnion)
                            .addComponent(BtnInterseccion)
                            .addComponent(btndiferencia)
                            .addComponent(btnConcatenacion)
                            .addComponent(btnPotencia)
                            .addComponent(btnInverso))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversoActionPerformed
        // TODO add your handling code here:
          Set<String> L1 = convertirTextoAConjunto(txtLenguaje1.getText());

    Set<String> resultado = calcularInverso(L1);
    txtResultado.setText("Inverso de L1: " + conjuntoAString(resultado));

    }//GEN-LAST:event_btnInversoActionPerformed

    private void txtLenguaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLenguaje2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLenguaje2ActionPerformed

    private void btnUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnionActionPerformed
        // TODO add your handling code here:
        Set<String> L1 = convertirTextoAConjunto(txtLenguaje1.getText());
    Set<String> L2 = convertirTextoAConjunto(txtLenguaje2.getText());

    Set<String> resultado = calcularUnion(L1, L2);
    txtResultado.setText("Unión: " + conjuntoAString(resultado));
    }//GEN-LAST:event_btnUnionActionPerformed

    private void BtnInterseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInterseccionActionPerformed
        // TODO add your handling code here:
      Set<String> L1 = convertirTextoAConjunto(txtLenguaje1.getText());
    Set<String> L2 = convertirTextoAConjunto(txtLenguaje2.getText());

    Set<String> resultado = calcularInterseccion(L1, L2);
    txtResultado.setText("Intersección: " + conjuntoAString(resultado));
    }//GEN-LAST:event_BtnInterseccionActionPerformed

    private void btndiferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiferenciaActionPerformed
        // TODO add your handling code here:
        Set<String> L1 = convertirTextoAConjunto(txtLenguaje1.getText());
    Set<String> L2 = convertirTextoAConjunto(txtLenguaje2.getText());

    Set<String> resultado = calcularDiferencia(L1, L2);
    txtResultado.setText("Diferencia (L1 - L2): " + conjuntoAString(resultado));
    }//GEN-LAST:event_btndiferenciaActionPerformed

    private void btnConcatenacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcatenacionActionPerformed
        // TODO add your handling code here:
            Set<String> L1 = convertirTextoAConjunto(txtLenguaje1.getText());
    Set<String> L2 = convertirTextoAConjunto(txtLenguaje2.getText());

    Set<String> resultado = calcularConcatenacion(L1, L2);
    txtResultado.setText("Concatenación: " + conjuntoAString(resultado));
    }//GEN-LAST:event_btnConcatenacionActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        // TODO add your handling code here:
         Set<String> L1 = convertirTextoAConjunto(txtLenguaje1.getText());

    String nTexto = txtPotencia.getText().trim();
    if (nTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa un número para la potencia.");
        return;
    }

    int n;
    try {
        n = Integer.parseInt(nTexto);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La potencia debe ser un número entero.");
        return;
    }

    Set<String> resultado = calcularPotencia(L1, n);
    txtResultado.setText("Potencia L1^" + n + ": " + conjuntoAString(resultado));

    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
 
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
Menu menu = new Menu();
    menu.setVisible(true);
    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInterseccion;
    private javax.swing.JButton btnConcatenacion;
    private javax.swing.JButton btnInverso;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnUnion;
    private javax.swing.JButton btndiferencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLenguaje1;
    private javax.swing.JTextField txtLenguaje2;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
